#!/bin/bash

function scrape() {
  echo "Scraping Constitución de $1..."
  echo "http://www.parlamento.gub.uy/Constituciones/Const${1:1}.htm"
  jruby ./script/scrape.rb "http://www.parlamento.gub.uy/Constituciones/Const${1:1}.htm" > $1.md
}

for i in 1830 1918 1934 1942 1952 1967 2004
do
  scrape $i
done

function compare() {
  local outputfile="diff_$1_$2.html"
  echo "Comparing files $1.md and $2.md into $outputfile"
  jruby ./script/diff.rb $1.md $2.md > $outputfile
}

compare 1830 1918
compare 1918 1934
compare 1934 1942
compare 1942 1952
compare 1967 2004
