#!/bin/bash

echo "Scraping Constitucion de 1830..."
./script/scrape.rb http://www.parlamento.gub.uy/Constituciones/Const830.htm > 1830.md
echo "Scraping Constitucion de 1918..."
./script/scrape.rb http://www.parlamento.gub.uy/Constituciones/Const918.htm > 1918.md
echo "Scraping Constitucion de 1934..."
./script/scrape.rb http://www.parlamento.gub.uy/Constituciones/Const934.htm > 1934.md
echo "Scraping Constitucion de 1942..."
./script/scrape.rb http://www.parlamento.gub.uy/Constituciones/Const942.htm > 1942.md
echo "Scraping Constitucion de 1952..."
./script/scrape.rb http://www.parlamento.gub.uy/Constituciones/Const952.htm > 1952.md
echo "Scraping Constitucion de 1967..."
./script/scrape.rb http://www.parlamento.gub.uy/Constituciones/Const967.htm > 1967.md
echo "Scraping Constitucion vigente..."
./script/scrape.rb http://www.parlamento.gub.uy/Constituciones/Const004.htm > vigente.md
